# Generated by Django 5.1.6 on 2025-06-28 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockModel",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StrategyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strateName", models.CharField(max_length=100)),
                (
                    "strateOperate",
                    models.IntegerField(
                        choices=[
                            (1, "重仓买入"),
                            (3, "轻仓买入"),
                            (-1, "卖出"),
                            (2, "中等仓位"),
                        ]
                    ),
                ),
                ("strateOperateTime", models.DateField()),
                ("strateDesc", models.CharField(max_length=1000)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_server.stockmodel",
                    ),
                ),
            ],
        ),
    ]
