# Generated by Django 5.1.6 on 2025-06-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategymodel",
            name="strateOperateTime",
            field=models.DateTimeField(),
        ),
    ]
