# Generated by Django 5.1.6 on 2025-02-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategymodel",
            name="strateDesc",
            field=models.CharField(max_length=100),
        ),
    ]
