# Generated by Django 5.1.6 on 2025-02-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0002_alter_strategymodel_stratedesc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategymodel",
            name="pnl_desc",
            field=models.CharField(max_length=1000),
        ),
    ]
