# Generated by Django 5.1.6 on 2025-02-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0003_alter_strategymodel_pnl_desc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="strategymodel",
            old_name="code",
            new_name="stock",
        ),
        migrations.RemoveField(
            model_name="stockmodel",
            name="id",
        ),
        migrations.AddField(
            model_name="strategymodel",
            name="strateOperate",
            field=models.CharField(
                choices=[("buy", "买入"), ("卖出", "sell")], default=None, max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="strategymodel",
            name="strateOperateTime",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="code",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="strategymodel",
            name="strateType",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
