# Generated by Django 5.1.6 on 2025-11-04 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0004_strategymodel_stratebacktestrate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("buy", "买入"), ("sell", "卖出")], max_length=4
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("shares", models.IntegerField()),
                ("fill_price", models.FloatField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
