# Generated by Django 5.1.6 on 2025-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bot_server",
            "0004_rename_code_strategymodel_stock_remove_stockmodel_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategymodel",
            name="strateOperate",
            field=models.CharField(
                choices=[("buy", "买入"), ("sell", "卖出")], max_length=10
            ),
        ),
    ]
