# Generated by Django 5.1.6 on 2025-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0005_strategyorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyorder",
            name="strategy_name",
            field=models.CharField(default="boll_rsi_v1", max_length=100),
        ),
    ]
