# Generated by Django 5.1.6 on 2025-11-10 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0006_strategyorder_strategy_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_name", models.CharField(max_length=100)),
                ("strategy_rate", models.FloatField(default=0)),
                ("strategy_win_count", models.IntegerField(default=0)),
                ("strategy_loss_count", models.IntegerField(default=0)),
                ("strategy_total_count", models.IntegerField(default=0)),
                ("strategy_total_profit", models.FloatField(default=0)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StrategySymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
