# Generated by Django 5.1.6 on 2025-02-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0006_remove_strategymodel_pnl_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategymodel",
            name="strateDesc",
            field=models.CharField(max_length=1000),
        ),
    ]
