# Generated by Django 5.1.6 on 2025-11-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0007_strategybase_strategysymbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategybase",
            name="risk_coefficient",
            field=models.IntegerField(choices=[(1, "稳健"), (2, "激进")], default=1),
        ),
    ]
