# Generated by Django 5.1.6 on 2025-02-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0007_alter_strategymodel_stratedesc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategymodel",
            name="pnl",
        ),
        migrations.RemoveField(
            model_name="strategymodel",
            name="strateType",
        ),
        migrations.RemoveField(
            model_name="strategymodel",
            name="winRate",
        ),
        migrations.AddField(
            model_name="strategymodel",
            name="strateName",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
