# Generated by Django 5.1.6 on 2025-02-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0008_remove_strategymodel_pnl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategymodel",
            name="strateType",
            field=models.IntegerField(choices=[(1, "稳健"), (2, "激进")], default=2),
            preserve_default=False,
        ),
    ]
