# Generated by Django 5.1.6 on 2025-12-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0008_strategybase_risk_coefficient"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategybase",
            name="strategy_desc",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
