# Generated by Django 5.1.6 on 2025-12-07 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0009_strategybase_strategy_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="StratepyTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("entry_date", models.DateField()),
                ("exit_date", models.DateField()),
                ("entry", models.FloatField()),
                ("exit", models.FloatField()),
                ("shares", models.IntegerField()),
                ("pnl", models.FloatField()),
                ("agg_pnl", models.FloatField()),
                ("return_pct", models.FloatField()),
                ("bars", models.IntegerField(default=0)),
                ("pnl_per_bar", models.FloatField(default=0)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="strategybase",
            name="risk_coefficient",
            field=models.IntegerField(
                choices=[(1, "稳健"), (2, "激进"), (3, "未知")], default=1
            ),
        ),
    ]
