# Generated by Django 5.1.6 on 2025-12-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_server", "0010_stratepytrade_alter_strategybase_risk_coefficient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("total_pnl", models.FloatField()),
                ("unrealized_pnl", models.FloatField()),
                ("total_return_pct", models.FloatField()),
                ("max_drawdown", models.FloatField()),
                ("max_drawdown_pct", models.FloatField()),
                ("avg_pnl", models.FloatField()),
                ("avg_return_pct", models.FloatField()),
                ("avg_profit_pct", models.FloatField()),
                ("avg_loss", models.FloatField()),
                ("avg_loss_pct", models.FloatField()),
                ("largest_win_pct", models.FloatField()),
                ("largest_loss", models.FloatField()),
                ("largest_loss_pct", models.FloatField()),
                ("sharpe", models.FloatField()),
                ("sortino", models.FloatField()),
                ("profit_factor", models.FloatField()),
                ("ulcer_index", models.FloatField()),
                ("upi", models.FloatField()),
                ("equity_r2", models.FloatField()),
                ("std_error", models.FloatField()),
            ],
        ),
    ]
